---

In [1]:
# gene level

In [2]:
library(AnnotationDbi)
library(org.Hs.eg.db)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(dplyr)
library(rtracklayer)

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Loading required package: IRanges

Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname




Loading required package: GenomicFeatures

Loading required package: GenomeInfoDb

Loading required package: GenomicRanges


Attaching package: ‘dplyr’


The following objects are masked from ‘package:GenomicRanges’:

    intersect, setdiff, union


The following object is masked from ‘package:GenomeInfoDb’:

    intersect


The following object is masked from ‘package:AnnotationDbi’:

    select


The following objects are masked from ‘package:IRanges’:

    collapse, desc, intersect, setdiff, slice, union


The following objects are masked from ‘package:S4Vectors’:

    first, intersect, rename, setdiff, setequal, union


The following object is masked from ‘package:Biobase’:

    combine


The following objects are masked from ‘package:BiocGenerics’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

##### first up regulated

In [1]:
mygenes <- read.delim("/usr/users/papantonis1/aman/rnaseq_data/upregulated_genes_deseq_auxincpi.txt", header = TRUE)
mygenes <- mygenes$hgnc_symbol

In [3]:
library(org.Hs.eg.db)

# Map gene symbols to Entrez IDs
mapped <- mapIds(org.Hs.eg.db,
                 keys = mygenes,
                 column = "ENTREZID",
                 keytype = "SYMBOL",
                 multiVals = "first")

# Remove NAs
entrez_ids <- na.omit(mapped)

'select()' returned 1:many mapping between keys and columns

In [4]:
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
gene_bodies <- genes(txdb)   # direct gene coordinates, keyed by Entrez IDs
gene_bodies <- gene_bodies[names(gene_bodies) %in% entrez_ids]

  2135 genes were dropped because they have exons located on both strands
  of the same reference sequence or on more than one reference sequence,
  so cannot be represented by a single genomic range.
  Use 'single.strand.genes.only=FALSE' to get all the genes in a
  GRangesList object, or use suppressMessages() to suppress this message.

In [5]:
library(GenomicFeatures)

txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene

# 1) One range per gene (Entrez IDs); ambiguous genes dropped by default
gene_bodies <- genes(txdb)                       # GRanges
gene_bodies <- gene_bodies[names(gene_bodies) %in% entrez_ids]

# 2) Convert to BED6 (0-based start)
tss_df <- as.data.frame(gene_bodies)
bed_gene_df <- data.frame(
  chrom      = tss_df$seqnames,
  chromStart = tss_df$start - 1L,   # BED is 0-based, half-open
  chromEnd   = tss_df$end,
  name       = tss_df$gene_id,      # <- correct column name
  score      = 0,
  strand     = as.character(tss_df$strand),
  stringsAsFactors = FALSE
)

stopifnot(nrow(bed_gene_df) == nrow(tss_df))     # sanity check

write.table(
  bed_gene_df,
  file = "upregulated_genelevel_genebodies_auxincpi.bed",
  sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE
)

  2135 genes were dropped because they have exons located on both strands
  of the same reference sequence or on more than one reference sequence,
  so cannot be represented by a single genomic range.
  Use 'single.strand.genes.only=FALSE' to get all the genes in a
  GRangesList object, or use suppressMessages() to suppress this message.

In [6]:
bed_gene_df

     chrom chromStart chromEnd  name      score strand
1    chr19  58345177   58362751 1         0     -
2    chr11  65044817   65058553 10004     0     -
3    chr9   21994138   22128103 100048912 0     +
4    chr16  68644992   68727468 1001      0     +
5    chr20  63953383   63956985 100113386 0     +
6    chrX  147909430  147911817 100126270 0     -
7    chr5  137647571  137647649 100126343 0     -
8    chr8   90958470   90985238 100127983 0     -
9    chr10  94278680   94287478 100128054 0     -
10   chr3  169939352  169966734 100128164 0     -
11   chr12  98512972   98516422 100128191 0     -
12   chr6  116494988  116545684 100128327 0     -
13   chr9  113102116  113111543 100128385 0     -
14   chr19  58002060   58011232 100128398 0     +
15   chr19   3539170    3544030 100128569 0     +
16   chr19  35399510   35419385 100128682 0     +
17   chr8   30382118   30385401 100128750 0     -
18   chr2  174025279  174027163 100128905 0     +
19   chr14  23099061   23104989 100128908 0     -
20   chr1   93591965   93610605 100129046 0     +
21   chr19  51415723   51417425 100129083 0     +
22   chr6  159760257  159762332 100129518 0     -
23   chr3  122886940  122892416 100129550 0     +
24   chr11  10541257   10599939 100129827 0     +
25   chr1   42784990   42816619 100129924 0     +
26   chr12  65851339   65882167 100129940 0     -
27   chr2  134735463  134918712 100129961 0     -
28   chr1  234757618  234760056 100130249 0     -
29   chr6   10409339   10416446 100130275 0     +
30   chr8   73241330   73259530 100130301 0     -
⋮    ⋮     ⋮          ⋮         ⋮         ⋮     ⋮
4503 chr17  63928737   63932336 974       0     -
4504 chr2   20032649   20051628 9741      0     -
4505 chr11   2376176    2397802 975       0     +
4506 chrX   68647665   68725842 9754      0     +
4507 chr19  14380500   14408725 976       0     +
4508 chr12 120687148  120701859 9761      0     +
4509 chr20   3162616    3173549 9762      0     -
4510 chr20   4780022    4823608 9770      0     -
4511 chr2    6917411    7068286 9781      0     +
4512 chr1   40620679   40687588 9783      0     -
4513 chr14  58427384   58551297 9786      0     +
4514 chr8   22219702   22232101 9796      0     -
4515 chr10  72059033   72089032 9806      0     -
4516 chr11  78215292   78418348 9846      0     -
4517 chr6   24544103   24646191 9856      0     -
4518 chr3   36826818   36945057 9881      0     -
4519 chr14 102362940  102502477 9895      0     +
4520 chr15  91099949   91302565 9899      0     +
4521 chr1  149903317  149917844 9900      0     -
4522 chr3    8980590    9363303 9901      0     -
4523 chr17  62627669   62693597 9902      0     +
4524 chr16  84368526   84464187 9914      0     +
4525 chr12   6493355    6531955 9918      0     +
4526 chr2   68679600   68826833 9938      0     +
4527 chr3   38039204   38124025 9940      0     +
4528 chr5  138285268  138338355 995       0     -
4529 chr16  22814161   22916338 9956      0     +
4530 chr12 100473707  100564414 9971      0     +
4531 chr16  68737291   68835537 999       0     +
4532 chr21  34364005   34371381 9992      0     +

##### now downregulated

In [7]:
mygenes <- read.delim("/usr/users/papantonis1/aman/rnaseq_data/downregulated_genes_deseq_auxincpi.txt", header = TRUE)
mygenes <- mygenes$hgnc_symbol

In [8]:
library(org.Hs.eg.db)

# Map gene symbols to Entrez IDs
mapped <- mapIds(org.Hs.eg.db,
                 keys = mygenes,
                 column = "ENTREZID",
                 keytype = "SYMBOL",
                 multiVals = "first")

# Remove NAs
entrez_ids <- na.omit(mapped)

'select()' returned 1:1 mapping between keys and columns

In [9]:
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene

gene_bodies <- genes(txdb)   # direct gene coordinates, keyed by Entrez IDs
gene_bodies <- gene_bodies[names(gene_bodies) %in% entrez_ids]

  2135 genes were dropped because they have exons located on both strands
  of the same reference sequence or on more than one reference sequence,
  so cannot be represented by a single genomic range.
  Use 'single.strand.genes.only=FALSE' to get all the genes in a
  GRangesList object, or use suppressMessages() to suppress this message.

In [ ]:
#as.data.frame(gene_bodies)

In [10]:
as.data.frame(gene_bodies)

          seqnames start     end       width  strand gene_id
100009676 chr3     101676424 101679217   2794 +      100009676
10001     chr14     70581257  70641204  59948 -      10001
100049716 chr12       630858    664196  33339 +      100049716
10008     chr11     74454841  74467729  12889 -      10008
10009     chrX     120250752 120258398   7647 +      10009
100093630 chr4     118278703 118285316   6614 +      100093630
10010     chr2     161136908 161236230  99323 +      10010
100101490 chr20     31547379  31548081    703 +      100101490
100113389 chr14     45110883  45110968     86 +      100113389
100113392 chr2     202291332 202291421     90 +      100113392
100125556 chr3     125916609 125930056  13448 +      100125556
100126331 chr1     117094643 117094728     86 +      100126331
100128071 chr1      32361270  32364278   3009 -      100128071
100128285 chr15     75727670  75738629  10960 -      100128285
100128511 chr10     21174014  21175048   1035 +      100128511
100128537 chr1     207760650 207879096 118447 -      100128537
100128594 chrX     103845151 103919548  74398 -      100128594
100128640 chr3      38451027  38454820   3794 -      100128640
100128788 chr16      2737076   2752600  15525 -      100128788
100128893 chr18     22166898  22169878   2981 -      100128893
100128927 chr14    104800596 104804712   4117 +      100128927
100129029 chr2     158658337 158735002  76666 -      100129029
100129196 chr1      30718504  30726827   8324 +      100129196
100129387 chr15     50354944  50357125   2182 +      100129387
100129484 chr7       5426277   5428927   2651 -      100129484
100129583 chr4      76214040  76283783  69744 +      100129583
100129726 chr2      43227210  43228855   1646 +      100129726
100129781 chr16     14301389  14331067  29679 +      100129781
100129878 chr18     49023703  49048474  24772 +      100129878
100130557 chr1      40690380  40692074   1695 -      100130557
⋮         ⋮        ⋮         ⋮         ⋮      ⋮      ⋮
9849      chr10     96129715  96205288  75574 +      9849
9852      chr3      36985043  36993131   8089 -      9852
9857      chr1     179954674 180114880 160207 +      9857
9861      chr3      64010550  64024010  13461 -      9861
9868      chr3     100363431 100401089  37659 -      9868
9869      chr1     150926263 150964744  38482 +      9869
987       chr4     150264435 151015727 751293 -      987
9871      chr4     118722823 118838683 115861 -      9871
9874      chr2     170990823 171231314 240492 -      9874
9877      chr1     203795623 203854124  58502 +      9877
9886      chr10     60869438  61001440 132003 -      9886
9891      chr12    106063345 106138954  75610 -      9891
9898      chr1     154220179 154271510  51332 +      9898
9903      chr1       6590724   6614607  23884 -      9903
9913      chr2      27650809  27663840  13032 -      9913
9923      chr1      22428838  22531157 102320 +      9923
9933      chr9       2720469   2844095 123627 -      9933
9937      chr10    113834725 113854383  19659 -      9937
9941      chr3      38496127  38542161  46035 +      9941
9945      chr5     180300698 180353336  52639 -      9945
9950      chr14     92794305  92839947  45643 +      9950
9953      chr17     14301081  14349404  48324 +      9953
9957      chr4      11393150  11429564  36415 -      9957
9960      chr15     63504511  63594640  90130 +      9960
9967      chr1      36224432  36305357  80926 +      9967
9972      chr6      17615035  17706925  91891 -      9972
9984      chr18       214520    268050  53531 -      9984
9987      chr4      82422565  82430462   7898 -      9987
9989      chr18      9546791   9615240  68450 -      9989
9997      chr22     50523568  50526461   2894 -      9997

In [11]:
# gene_bodies is a GRanges from: gene_bodies <- genes(txdb)
tss_df <- as.data.frame(gene_bodies)   # cols: seqnames, start, end, strand, gene_id, ...

# Build BED6 (0-based, half-open)
bed_gene_df <- data.frame(
  chrom      = tss_df$seqnames,
  chromStart = as.integer(tss_df$start) - 1L,   # BED is 0-based
  chromEnd   = as.integer(tss_df$end),
  name       = as.character(tss_df$gene_id),    # <-- FIXED
  score      = 0,
  strand     = as.character(tss_df$strand),
  stringsAsFactors = FALSE
)

write.table(
  bed_gene_df,
  file = "downregulated_gene_level_genebodies_auxincpi.bed",
  sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE
)

In [12]:
bed_gene_df

     chrom chromStart chromEnd  name      score strand
1    chr3  101676423  101679217 100009676 0     +
2    chr14  70581256   70641204 10001     0     -
3    chr12    630857     664196 100049716 0     +
4    chr11  74454840   74467729 10008     0     -
5    chrX  120250751  120258398 10009     0     +
6    chr4  118278702  118285316 100093630 0     +
7    chr2  161136907  161236230 10010     0     +
8    chr20  31547378   31548081 100101490 0     +
9    chr14  45110882   45110968 100113389 0     +
10   chr2  202291331  202291421 100113392 0     +
11   chr3  125916608  125930056 100125556 0     +
12   chr1  117094642  117094728 100126331 0     +
13   chr1   32361269   32364278 100128071 0     -
14   chr15  75727669   75738629 100128285 0     -
15   chr10  21174013   21175048 100128511 0     +
16   chr1  207760649  207879096 100128537 0     -
17   chrX  103845150  103919548 100128594 0     -
18   chr3   38451026   38454820 100128640 0     -
19   chr16   2737075    2752600 100128788 0     -
20   chr18  22166897   22169878 100128893 0     -
21   chr14 104800595  104804712 100128927 0     +
22   chr2  158658336  158735002 100129029 0     -
23   chr1   30718503   30726827 100129196 0     +
24   chr15  50354943   50357125 100129387 0     +
25   chr7    5426276    5428927 100129484 0     -
26   chr4   76214039   76283783 100129583 0     +
27   chr2   43227209   43228855 100129726 0     +
28   chr16  14301388   14331067 100129781 0     +
29   chr18  49023702   49048474 100129878 0     +
30   chr1   40690379   40692074 100130557 0     -
⋮    ⋮     ⋮          ⋮         ⋮         ⋮     ⋮
3007 chr10  96129714   96205288 9849      0     +
3008 chr3   36985042   36993131 9852      0     -
3009 chr1  179954673  180114880 9857      0     +
3010 chr3   64010549   64024010 9861      0     -
3011 chr3  100363430  100401089 9868      0     -
3012 chr1  150926262  150964744 9869      0     +
3013 chr4  150264434  151015727 987       0     -
3014 chr4  118722822  118838683 9871      0     -
3015 chr2  170990822  171231314 9874      0     -
3016 chr1  203795622  203854124 9877      0     +
3017 chr10  60869437   61001440 9886      0     -
3018 chr12 106063344  106138954 9891      0     -
3019 chr1  154220178  154271510 9898      0     +
3020 chr1    6590723    6614607 9903      0     -
3021 chr2   27650808   27663840 9913      0     -
3022 chr1   22428837   22531157 9923      0     +
3023 chr9    2720468    2844095 9933      0     -
3024 chr10 113834724  113854383 9937      0     -
3025 chr3   38496126   38542161 9941      0     +
3026 chr5  180300697  180353336 9945      0     -
3027 chr14  92794304   92839947 9950      0     +
3028 chr17  14301080   14349404 9953      0     +
3029 chr4   11393149   11429564 9957      0     -
3030 chr15  63504510   63594640 9960      0     +
3031 chr1   36224431   36305357 9967      0     +
3032 chr6   17615034   17706925 9972      0     -
3033 chr18    214519     268050 9984      0     -
3034 chr4   82422564   82430462 9987      0     -
3035 chr18   9546790    9615240 9989      0     -
3036 chr22  50523567   50526461 9997      0     -

In [ ]:
# gene-id stored as column "name"