In [1]:
import pandas as pd
from pybedtools import BedTool

# Read BEDPE file (assume first 6 columns: chrom1, start1, end1, chrom2, start2, end2, loop_id in col 6 or 7)
bedpe = pd.read_csv('/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/jupyter_notes/ml_5_multiclassmodel.csv', sep=',')

# For each row, get min(start1, start2) as loop_start, max(end1, end2) as loop_end
bedpe['loop_chr'] = bedpe['chr1']  # assuming intra-chromosomal
bedpe['loop_start'] = bedpe[['start1', 'start2']].min(axis=1) # The first anchor might not be leftmost, so we take the minimum of both anchor starts
bedpe['loop_end'] = bedpe[['end1', 'end2']].max(axis=1) # The second anchor might not be rightmost, so we take the maximum of both anchor ends.

# Now create BED DataFrame
loops_bed_df = bedpe[['loop_chr', 'loop_start', 'loop_end']]

# Convert to BedTool
loops_bed = BedTool.from_dataframe(loops_bed_df)

In [2]:
bedpe

,Unnamed: 0,chr1,start1,end1,chr2,start2,end2,status,ctrl_signal,rbp1_signal,...,GC_diff,E1_anchor1_ctrl,E1_anchor1_rbp1,E1_anchor2_ctrl,E1_anchor2_rbp1,delta_E1_anchor1,delta_E1_anchor2,loop_chr,loop_start,loop_end
0,0,chr1,1952500,1957500,chr1,2042500,2047500,shared,NaN,NaN,...,0.0494,NaN,NaN,NaN,NaN,NaN,NaN,chr1,1952500,2047500
1,1,chr1,2202500,2207500,chr1,2382500,2387500,shared,NaN,NaN,...,0.0578,NaN,NaN,NaN,NaN,NaN,NaN,chr1,2202500,2387500
2,2,chr1,2412500,2417500,chr1,2552500,2557500,shared,NaN,NaN,...,0.0102,NaN,NaN,NaN,NaN,NaN,NaN,chr1,2412500,2557500
3,3,chr1,3490000,3495000,chr1,3615000,3620000,shared,NaN,NaN,...,0.0948,NaN,NaN,NaN,NaN,NaN,NaN,chr1,3490000,3620000
4,4,chr1,3565000,3570000,chr1,3615000,3620000,shared,NaN,NaN,...,0.0842,NaN,NaN,NaN,NaN,NaN,NaN,chr1,3565000,3620000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32272,32272,chrY,10945000,10950000,chrY,11290000,11295000,gained,0.006078,0.006342,...,0.0226,-0.064836,-0.140925,0.270996,0.177009,-0.076090,-0.093987,chrY,10945000,11295000
32273,32273,chrY,10982500,10987500,chrY,11292500,11297500,gained,0.007661,0.005159,...,0.0026,0.120802,-0.100746,0.270996,0.177009,-0.221548,-0.093987,chrY,10982500,11297500
32274,32274,chrY,11292500,11297500,chrY,11722500,11727500,gained,0.001017,0.001021,...,0.0854,0.270996,0.177009,0.409095,0.332632,-0.093987,-0.076464,chrY,11292500,11727500
32275,32275,chrY,11530000,11535000,chrY,11760000,11765000,gained,0.004674,0.006621,...,0.0120,-1.192141,-1.204536,-1.229772,-1.167283,-0.012394,0.062489,chrY,11530000,11765000
32276,32276,chrY,19432500,19437500,chrY,20742500,20747500,gained,0.007706,0.016045,...,0.0254,0.435165,0.432883,0.380603,0.539909,-0.002283,0.159306,chrY,19432500,20747500

In [3]:
loops_bed_df

      loop_chr  loop_start  loop_end
0         chr1     1952500   2047500
1         chr1     2202500   2387500
2         chr1     2412500   2557500
3         chr1     3490000   3620000
4         chr1     3565000   3620000
...        ...         ...       ...
32272     chrY    10945000  11295000
32273     chrY    10982500  11297500
32274     chrY    11292500  11727500
32275     chrY    11530000  11765000
32276     chrY    19432500  20747500

[32277 rows x 3 columns]

In [4]:
up = pd.read_csv('/usr/users/papantonis1/aman/rnaseq_data/upregulated_transcript_level_genebodies.bed', sep='\t')
down = pd.read_csv('/usr/users/papantonis1/aman/rnaseq_data/downregulated_transcript_level_genebodies.bed', sep='\t')
concat = pd.concat([up, down])
concat

,chr1,11934204,11958620,ENST00000485046.5,0,+,960583,965719,ENST00000338591.8
0,chr1,11934693.0,11952691.0,ENST00000449038.5,0,+,NaN,NaN,NaN
1,chr1,11934716.0,11975537.0,ENST00000196061.5,0,+,NaN,NaN,NaN
2,chr1,11934733.0,11954767.0,ENST00000358133.5,0,+,NaN,NaN,NaN
3,chr1,11934742.0,11957943.0,ENST00000429000.6,0,+,NaN,NaN,NaN
4,chr1,11954300.0,11958593.0,ENST00000465920.1,0,+,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
679,chr20,NaN,NaN,NaN,0,-,63699511.0,63706053.0,ENST00000610774.1
680,chr20,NaN,NaN,NaN,0,-,63700053.0,63708025.0,ENST00000607873.1
681,chr20,NaN,NaN,NaN,0,-,63701696.0,63706874.0,ENST00000609537.5
682,chr20,NaN,NaN,NaN,0,-,63705578.0,63706738.0,ENST00000424545.2
683,chr21,NaN,NaN,NaN,0,-,32377186.0,32377322.0,ENST00000363922.1

In [5]:
colnames = [concat.columns[1], concat.columns[2]]
concat.drop_duplicates(subset=colnames)

,chr1,11934204,11958620,ENST00000485046.5,0,+,960583,965719,ENST00000338591.8
0,chr1,11934693.0,11952691.0,ENST00000449038.5,0,+,NaN,NaN,NaN
1,chr1,11934716.0,11975537.0,ENST00000196061.5,0,+,NaN,NaN,NaN
2,chr1,11934733.0,11954767.0,ENST00000358133.5,0,+,NaN,NaN,NaN
3,chr1,11934742.0,11957943.0,ENST00000429000.6,0,+,NaN,NaN,NaN
4,chr1,11954300.0,11958593.0,ENST00000465920.1,0,+,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2141,chrX,112823136.0,112840683.0,ENST00000462114.1,0,-,NaN,NaN,NaN
2142,chrX,136665546.0,136767343.0,ENST00000370620.5,0,-,NaN,NaN,NaN
2143,chrX,136665546.0,136768627.0,ENST00000370622.5,0,-,NaN,NaN,NaN
2144,chrX,136665549.0,136780932.0,ENST00000250617.7,0,-,NaN,NaN,NaN
0,chr1,NaN,NaN,NaN,0,+,961448.0,962478.0,ENST00000463212.1