In [2]:
# With this notebook I have log2fc values for the genes across intron lvl, exon lvl, & deseq lvl

In [3]:
import numpy as np

##### Upregulated

In [4]:
import pandas as pd

# Load the mega upregulated list (common upregulated genes)
mega_up = pd.read_csv("/usr/users/papantonis1/aman/rnaseq_data/mega_upregulated.tsv", sep="\t")
common_genes_up = mega_up.iloc[:, 0].astype(str).str.strip()
# Load log2FC
exon_df = pd.read_csv("/usr/users/papantonis1/aman/rnaseq_data/upregulated_genes_exons_irnaseqCM.txt", sep="\t")
intron_df = pd.read_csv("/usr/users/papantonis1/aman/rnaseq_data/upregulated_genes_introns_irnaseqCM.txt", sep="\t")
deseq_df = pd.read_csv("/usr/users/papantonis1/aman/rnaseq_data/upregulated_genes_deseq.txt", sep="\t")

# Standardize column names
exon_df = exon_df.rename(columns={'log2FC': 'log2fc_exon'})
intron_df = intron_df.rename(columns={'log2FC': 'log2fc_intron'})
deseq_df = deseq_df.rename(columns={'log2FC': 'log2fc_deseq'})

exon_df = exon_df.rename(columns={'ensembl': 'hgnc_symbol'})
intron_df = intron_df.rename(columns={'ensembl': 'hgnc_symbol'})

# Merge based on common genes
merged_up = pd.DataFrame({'hgnc_symbol': common_genes_up})
merged_up = merged_up.merge(exon_df[['hgnc_symbol', 'log2fc_exon']], on='hgnc_symbol', how='left')
merged_up = merged_up.merge(intron_df[['hgnc_symbol', 'log2fc_intron']], on='hgnc_symbol', how='left')
merged_up = merged_up.merge(deseq_df[['hgnc_symbol', 'log2fc_deseq']], on='hgnc_symbol', how='left')

In [5]:
merged_up

    hgnc_symbol  log2fc_exon  log2fc_intron  log2fc_deseq
0         ASH2L     0.621407            NaN           NaN
1        CSRNP2          NaN       0.628998           NaN
2         HLA-B          NaN            NaN      0.826139
3           JUP          NaN            NaN      0.665529
4         CAPN5          NaN            NaN      0.672428
..          ...          ...            ...           ...
209      DNASE2          NaN            NaN      0.618205
210       KIFC1          NaN            NaN      0.657723
211      CREBBP          NaN            NaN      0.653104
212      SLC7A1     0.628871            NaN      0.705278
213      SLC9A1     0.659208            NaN      0.756630

[214 rows x 4 columns]

In [6]:
merged_up

    hgnc_symbol  log2fc_exon  log2fc_intron  log2fc_deseq
0         ASH2L     0.621407            NaN           NaN
1        CSRNP2          NaN       0.628998           NaN
2         HLA-B          NaN            NaN      0.826139
3           JUP          NaN            NaN      0.665529
4         CAPN5          NaN            NaN      0.672428
..          ...          ...            ...           ...
209      DNASE2          NaN            NaN      0.618205
210       KIFC1          NaN            NaN      0.657723
211      CREBBP          NaN            NaN      0.653104
212      SLC7A1     0.628871            NaN      0.705278
213      SLC9A1     0.659208            NaN      0.756630

[214 rows x 4 columns]

##### verifying

In [7]:
len(merged_up[
    merged_up['log2fc_exon'].notna() &
    merged_up['log2fc_intron'].isna() &
    merged_up['log2fc_deseq'].isna()
])

11

In [8]:
len(merged_up[
    merged_up['log2fc_exon'].isna() &
    merged_up['log2fc_intron'].notna() &
    merged_up['log2fc_deseq'].isna()
])

16

In [9]:
len(merged_up[
    merged_up['log2fc_exon'].isna() &
    merged_up['log2fc_intron'].isna() &
    merged_up['log2fc_deseq'].notna()
])

105

In [10]:
merged_up.to_csv("mega_upregulated_withall3_log2fc.tsv", sep="\t", index=False)

##### Downregulated

In [11]:
# Load the mega upregulated list (common upregulated genes)
mega_down = pd.read_csv("/usr/users/papantonis1/aman/rnaseq_data/mega_downregulated.tsv", sep="\t")
common_genes_down = mega_down.iloc[:, 0].astype(str).str.strip()
# Load log2FC
exon_df = pd.read_csv("/usr/users/papantonis1/aman/rnaseq_data/downregulated_genes_exons_irnaseqCM.txt", sep="\t")
intron_df = pd.read_csv("/usr/users/papantonis1/aman/rnaseq_data/downregulated_genes_introns_irnaseqCM.txt", sep="\t")
deseq_df = pd.read_csv("/usr/users/papantonis1/aman/rnaseq_data/downregulated_genes_deseq.txt", sep="\t")

# Standardize column names
exon_df = exon_df.rename(columns={'log2FC': 'log2fc_exon'})
intron_df = intron_df.rename(columns={'log2FC': 'log2fc_intron'})
deseq_df = deseq_df.rename(columns={'log2FC': 'log2fc_deseq'})

exon_df = exon_df.rename(columns={'ensembl': 'hgnc_symbol'})
intron_df = intron_df.rename(columns={'ensembl': 'hgnc_symbol'})

# Merge based on common genes
merged_down = pd.DataFrame({'hgnc_symbol': common_genes_down})
merged_down = merged_down.merge(exon_df[['hgnc_symbol', 'log2fc_exon']], on='hgnc_symbol', how='left')
merged_down = merged_down.merge(intron_df[['hgnc_symbol', 'log2fc_intron']], on='hgnc_symbol', how='left')
merged_down = merged_down.merge(deseq_df[['hgnc_symbol', 'log2fc_deseq']], on='hgnc_symbol', how='left')

In [12]:
merged_down

    hgnc_symbol  log2fc_exon  log2fc_intron  log2fc_deseq
0       SNORA53          NaN            NaN     -0.693060
1        TSPAN4          NaN      -0.673865           NaN
2          POLE          NaN      -0.849333           NaN
3       SNORD3C          NaN            NaN     -0.966969
4        GABBR1          NaN            NaN     -0.638401
..          ...          ...            ...           ...
106       WDR76    -0.675459            NaN           NaN
107       MECOM          NaN      -0.717295           NaN
108        ING2          NaN            NaN     -0.730267
109         MYB          NaN      -0.971711     -0.897640
110      RNF207    -0.805604            NaN     -0.732746

[111 rows x 4 columns]

In [13]:
valid_pairs = merged_down[['log2fc_exon', 'log2fc_intron']].dropna()
print("Valid exon–intron pairs:", len(valid_pairs))

valid_pairs = merged_down[['log2fc_exon', 'log2fc_deseq']].dropna()
print("Valid exon–deseq pairs:", len(valid_pairs))

valid_pairs = merged_down[['log2fc_intron', 'log2fc_deseq']].dropna()
print("Valid intron–deseq pairs:", len(valid_pairs))

Valid exon–intron pairs: 7
Valid exon–deseq pairs: 15
Valid intron–deseq pairs: 7

In [18]:
from scipy.stats import spearmanr

subset = merged_down[['log2fc_exon', 'log2fc_deseq']].dropna()
rho, p = spearmanr(subset['log2fc_exon'], subset['log2fc_deseq'])
print("Spearman (exon vs deseq):", rho, p)

Spearman (exon vs deseq): 0.8928571428571428 7.4947360645682566e-06

In [19]:
from scipy.stats import ttest_rel

subset = merged_down[['log2fc_intron', 'log2fc_deseq']].dropna()
t_stat, p = ttest_rel(subset['log2fc_intron'], subset['log2fc_deseq'])
print("Paired t-test (intron vs deseq):", t_stat, p)

Paired t-test (intron vs deseq): -2.3702054796965597 0.055505121398509785

In [20]:
from scipy.stats import wilcoxon

subset = merged_down[['log2fc_intron', 'log2fc_deseq']].dropna()
w_stat, p = wilcoxon(subset['log2fc_intron'], subset['log2fc_deseq'])
print("Wilcoxon test (intron vs deseq):", w_stat, p)

Wilcoxon test (intron vs deseq): 0.0 0.015625

In [21]:
### intron vs exon

from scipy.stats import spearmanr

subset = merged_down[['log2fc_intron', 'log2fc_exon']].dropna()
rho, p = spearmanr(subset['log2fc_intron'], subset['log2fc_exon'])
print("Spearman (intron vs exon):", rho, p)

Spearman (intron vs exon): 0.8214285714285715 0.023448808345691505

In [22]:
from scipy.stats import ttest_rel

subset = merged_down[['log2fc_intron', 'log2fc_exon']].dropna()
t_stat, p = ttest_rel(subset['log2fc_intron'], subset['log2fc_exon'])
print("Paired t-test (intron vs exon):", t_stat, p)

Paired t-test (intron vs exon): -2.5863001658884377 0.04141726978778706

In [23]:
from scipy.stats import wilcoxon

subset = merged_down[['log2fc_intron', 'log2fc_exon']].dropna()
w_stat, p = wilcoxon(subset['log2fc_intron'], subset['log2fc_exon'])
print("Wilcoxon (intron vs exon):", w_stat, p)

Wilcoxon (intron vs exon): 3.0 0.078125

##### verification

In [14]:
len(merged_down[
    merged_down['log2fc_exon'].notna() &
    merged_down['log2fc_intron'].isna() &
    merged_down['log2fc_deseq'].isna()
])

17

In [15]:
len(merged_down[
    merged_down['log2fc_exon'].isna() &
    merged_down['log2fc_intron'].notna() &
    merged_down['log2fc_deseq'].isna()
])

26

In [16]:
len(merged_down[
    merged_down['log2fc_exon'].isna() &
    merged_down['log2fc_intron'].isna() &
    merged_down['log2fc_deseq'].notna()
])

45

##### export

In [17]:
merged_down.to_csv("mega_downregulated_withall3_log2fc.tsv", sep="\t", index=False)