---

In [41]:
library(AnnotationDbi)
library(org.Hs.eg.db)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(dplyr)
library(rtracklayer)

## Transcript -level genebody

##### first up regulated

In [42]:
mygenes <- read.delim("/usr/users/papantonis1/aman/rnaseq_data/upregulated_genes_deseq.txt", header = TRUE)
mygenes <- mygenes$hgnc_symbol

In [43]:
library(org.Hs.eg.db)

# Map gene symbols to Entrez IDs
mapped <- mapIds(org.Hs.eg.db,
                 keys = mygenes,
                 column = "ENTREZID",
                 keytype = "SYMBOL",
                 multiVals = "first")

# Remove NAs
entrez_ids <- na.omit(mapped)

'select()' returned 1:1 mapping between keys and columns

In [44]:
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
mygenes.transcripts <- subset(
  transcripts(txdb, columns = c("tx_id", "tx_name", "gene_id")),
  gene_id %in% entrez_ids
)

In [45]:
gene_bodies <- as.data.frame(mygenes.transcripts)

In [46]:
#as.data.frame(gene_bodies)

In [47]:
library(dplyr)

# This regex matches only chr1-chr22, chrX, chrY, chrM (no underscores or suffixes)
gene_bodies <- gene_bodies %>%
  filter(grepl("^chr([1-9]|1[0-9]|2[0-2]|X|Y|M)$", seqnames))

In [48]:
as.data.frame(gene_bodies)

     seqnames start     end       width  strand tx_id  tx_name
1    chr1     11934205  11958620   24416 +       955   ENST00000485046.5
2    chr1     11934694  11952691   17998 +       956   ENST00000449038.5
3    chr1     11934717  11975537   40821 +       957   ENST00000196061.5
4    chr1     11934734  11954767   20034 +       958   ENST00000358133.5
5    chr1     11934743  11957943   23201 +       959   ENST00000429000.6
6    chr1     11954301  11958593    4293 +       960   ENST00000465920.1
7    chr1     11964688  11975538   10851 +       961   ENST00000491536.5
8    chr1     11964702  11966414    1713 +       962   ENST00000470133.1
9    chr1     11971543  11975536    3994 +       963   ENST00000481933.1
10   chr1     22710839  22891265  180427 +      1566   ENST00000544305.5
11   chr1     22710839  22921500  210662 +      1567   ENST00000374630.8
12   chr1     22710965  22921500  210536 +      1568   ENST00000400191.7
13   chr1     22710970  22914270  203301 +      1569   ENST00000374632.7
14   chr1     22775178  22913752  138575 +      1571   ENST00000374627.1
15   chr1     22800240  22896478   96239 +      1572   ENST00000465676.1
16   chr1     22865159  22882840   17682 +      1573   ENST00000490436.1
17   chr1     28369582  28459239   89658 +      2093   ENST00000633371.1
18   chr1     28369609  28466584   96976 +      2094   ENST00000632202.1
19   chr1     28369710  28497545  127836 +      2095   ENST00000632421.1
20   chr1     28369739  28467241   97503 +      2096   ENST00000463428.5
21   chr1     28369740  28500364  130625 +      2097   ENST00000373839.8
22   chr1     28369744  28497156  127413 +      2098   ENST00000493669.2
23   chr1     28438151  28460286   22136 +      2099   ENST00000633167.1
24   chr1     28438171  28497303   59133 +      2100   ENST00000373836.4
25   chr1     28491695  28500364    8670 +      2103   ENST00000632964.1
26   chr1     37692481  37709713   17233 +      2670   ENST00000327331.2
27   chr1     37692516  37709719   17204 +      2671   ENST00000373055.6
28   chr1     43358981  43363203    4223 +      3136   ENST00000310955.11
29   chr1     43359013  43363203    4191 +      3137   ENST00000372462.1
30   chr1     43359767  43360864    1098 +      3138   ENST00000478882.1
⋮    ⋮        ⋮         ⋮         ⋮      ⋮      ⋮      ⋮
2117 chrX     101485456 101533459  48004 +      246138 ENST00000442270.5
2118 chrX     101485475 101533459  47985 +      246139 ENST00000354842.5
2119 chrX     152830967 152869363  38397 +      247435 ENST00000440023.5
2120 chrX     152830997 152867647  36651 +      247436 ENST00000432467.1
2121 chrX     152831063 152869729  38667 +      247437 ENST00000370274.8
2122 chrX     152898067 152973474  75408 +      247438 ENST00000695776.1
2123 chrX     152914442 152973480  59039 +      247439 ENST00000449285.6
2124 chrX     152914442 152973481  59040 +      247440 ENST00000539731.6
2125 chrX     152914453 152973471  59019 +      247441 ENST00000370268.8
2126 chrX     152914490 152970541  56052 +      247442 ENST00000436731.6
2127 chrX     152914490 152973481  58992 +      247443 ENST00000318504.12
2128 chrX     152914490 152973481  58992 +      247444 ENST00000535861.6
2129 chrX     152917865 152973473  55609 +      247445 ENST00000318529.13
2130 chrX     152920349 152973473  53125 +      247446 ENST00000426821.6
2131 chrX     152920707 152959841  39135 +      247447 ENST00000447792.2
2132 chrX     152941701 152973472  31772 +      247448 ENST00000454925.1
2133 chrX      38149336  38220924  71589 -      248573 ENST00000432886.6
2134 chrX      38149336  38220924  71589 -      248574 ENST00000538295.5
2135 chrX      38149336  38220924  71589 -      248575 ENST00000544439.5
2136 chrX      38149339  38220871  71533 -      248576 ENST00000378533.4
2137 chrX      38149351  38160098  10748 -      248577 ENST00000479015.1
2138 chrX      38149631  38154581   4951 -      248578 ENST00000461865.1
2139 chrX     112774503 112840815  66313 -      250577 ENST00000304758.5
2140 chrX     112774877 112840831  65955 -      250578 ENST00000371959.9
2141 chrX     112778512 112822536  44025 -      250579 ENST00000371962.5
2142 chrX     112780355 112822584  42230 -      250580 ENST00000371958.1
2143 chrX     112823137 112840683  17547 -      250582 ENST00000462114.1
2144 chrX     136665547 136767343 101797 -      251113 ENST00000370620.5
2145 chrX     136665547 136768627 103081 -      251114 ENST00000370622.5
2146 chrX     136665550 136780932 115383 -      251115 ENST00000250617.7
     gene_id
1     5351
2     5351
3     5351
4     5351
5     5351
6     5351
7     5351
8     5351
9     5351
10    2048
11    2048
12    2048
13    2048
14    2048
15    2048
16    2048
17   65979
18   65979
19   65979
20   65979
21   65979
22   65979
23   65979
24   65979
25   65979
26   55143
27   55143
28     991
29     991
30     991
⋮    ⋮
2117 100131755
2118 100131755
2119     50814
2120     50814
2121     50814
2122      7739
2123      7739
2124      7739
2125      7739
2126      7739
2127      7739
2128      7739
2129      7739
2130      7739
2131      7739
2132      7739
2133      8406
2134      8406
2135      8406
2136      8406
2137      8406
2138      8406
2139    154796
2140    154796
2141    154796
2142    154796
2143    154796
2144      9459
2145      9459
2146      9459

In [49]:
# Converting to dataframe
tss_df <- as.data.frame(gene_bodies)

# Creating a .bed like table
bed_gene_df <- data.frame(
  chrom = tss_df$seqnames,
  chromStart = tss_df$start - 1,  # BED is 0-based
  chromEnd = tss_df$end,          
  name = tss_df$tx_name,         
  score = 0,
  strand = tss_df$strand
)
#export
write.table(
  bed_gene_df,
  file = "upregulated_transcript_level_genebodies.bed",
  sep = "\t",
  quote = FALSE,
  row.names = FALSE,
  col.names = FALSE
)

In [50]:
#tss_df

In [51]:
bed_gene_df

     chrom chromStart chromEnd  name               score strand
1    chr1  11934204   11958620  ENST00000485046.5  0     +
2    chr1  11934693   11952691  ENST00000449038.5  0     +
3    chr1  11934716   11975537  ENST00000196061.5  0     +
4    chr1  11934733   11954767  ENST00000358133.5  0     +
5    chr1  11934742   11957943  ENST00000429000.6  0     +
6    chr1  11954300   11958593  ENST00000465920.1  0     +
7    chr1  11964687   11975538  ENST00000491536.5  0     +
8    chr1  11964701   11966414  ENST00000470133.1  0     +
9    chr1  11971542   11975536  ENST00000481933.1  0     +
10   chr1  22710838   22891265  ENST00000544305.5  0     +
11   chr1  22710838   22921500  ENST00000374630.8  0     +
12   chr1  22710964   22921500  ENST00000400191.7  0     +
13   chr1  22710969   22914270  ENST00000374632.7  0     +
14   chr1  22775177   22913752  ENST00000374627.1  0     +
15   chr1  22800239   22896478  ENST00000465676.1  0     +
16   chr1  22865158   22882840  ENST00000490436.1  0     +
17   chr1  28369581   28459239  ENST00000633371.1  0     +
18   chr1  28369608   28466584  ENST00000632202.1  0     +
19   chr1  28369709   28497545  ENST00000632421.1  0     +
20   chr1  28369738   28467241  ENST00000463428.5  0     +
21   chr1  28369739   28500364  ENST00000373839.8  0     +
22   chr1  28369743   28497156  ENST00000493669.2  0     +
23   chr1  28438150   28460286  ENST00000633167.1  0     +
24   chr1  28438170   28497303  ENST00000373836.4  0     +
25   chr1  28491694   28500364  ENST00000632964.1  0     +
26   chr1  37692480   37709713  ENST00000327331.2  0     +
27   chr1  37692515   37709719  ENST00000373055.6  0     +
28   chr1  43358980   43363203  ENST00000310955.11 0     +
29   chr1  43359012   43363203  ENST00000372462.1  0     +
30   chr1  43359766   43360864  ENST00000478882.1  0     +
⋮    ⋮     ⋮          ⋮         ⋮                  ⋮     ⋮
2117 chrX  101485455  101533459 ENST00000442270.5  0     +
2118 chrX  101485474  101533459 ENST00000354842.5  0     +
2119 chrX  152830966  152869363 ENST00000440023.5  0     +
2120 chrX  152830996  152867647 ENST00000432467.1  0     +
2121 chrX  152831062  152869729 ENST00000370274.8  0     +
2122 chrX  152898066  152973474 ENST00000695776.1  0     +
2123 chrX  152914441  152973480 ENST00000449285.6  0     +
2124 chrX  152914441  152973481 ENST00000539731.6  0     +
2125 chrX  152914452  152973471 ENST00000370268.8  0     +
2126 chrX  152914489  152970541 ENST00000436731.6  0     +
2127 chrX  152914489  152973481 ENST00000318504.12 0     +
2128 chrX  152914489  152973481 ENST00000535861.6  0     +
2129 chrX  152917864  152973473 ENST00000318529.13 0     +
2130 chrX  152920348  152973473 ENST00000426821.6  0     +
2131 chrX  152920706  152959841 ENST00000447792.2  0     +
2132 chrX  152941700  152973472 ENST00000454925.1  0     +
2133 chrX   38149335   38220924 ENST00000432886.6  0     -
2134 chrX   38149335   38220924 ENST00000538295.5  0     -
2135 chrX   38149335   38220924 ENST00000544439.5  0     -
2136 chrX   38149338   38220871 ENST00000378533.4  0     -
2137 chrX   38149350   38160098 ENST00000479015.1  0     -
2138 chrX   38149630   38154581 ENST00000461865.1  0     -
2139 chrX  112774502  112840815 ENST00000304758.5  0     -
2140 chrX  112774876  112840831 ENST00000371959.9  0     -
2141 chrX  112778511  112822536 ENST00000371962.5  0     -
2142 chrX  112780354  112822584 ENST00000371958.1  0     -
2143 chrX  112823136  112840683 ENST00000462114.1  0     -
2144 chrX  136665546  136767343 ENST00000370620.5  0     -
2145 chrX  136665546  136768627 ENST00000370622.5  0     -
2146 chrX  136665549  136780932 ENST00000250617.7  0     -

##### now downregulated

In [52]:
mygenes <- read.delim("/usr/users/papantonis1/aman/rnaseq_data/downregulated_genes_deseq.txt", header = TRUE)
mygenes <- mygenes$hgnc_symbol

In [53]:
library(org.Hs.eg.db)

# Map gene symbols to Entrez IDs
mapped <- mapIds(org.Hs.eg.db,
                 keys = mygenes,
                 column = "ENTREZID",
                 keytype = "SYMBOL",
                 multiVals = "first")

# Remove NAs
entrez_ids <- na.omit(mapped)

'select()' returned 1:1 mapping between keys and columns

In [54]:
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
mygenes.transcripts <- subset(
  transcripts(txdb, columns = c("tx_id", "tx_name", "gene_id")),
  gene_id %in% entrez_ids
)

In [55]:
gene_bodies <- as.data.frame(mygenes.transcripts)

In [56]:
#as.data.frame(gene_bodies)

In [57]:
library(dplyr)

# This regex matches only chr1-chr22, chrX, chrY, chrM (no underscores or suffixes)
gene_bodies <- gene_bodies %>%
  filter(grepl("^chr([1-9]|1[0-9]|2[0-2]|X|Y|M)$", seqnames))

In [58]:
as.data.frame(gene_bodies)

    seqnames start    end      width strand tx_id  tx_name            gene_id
1   chr1      960584   965719   5136 +      130    ENST00000338591.8  339451
2   chr1      961449   962478   1030 +      131    ENST00000463212.1  339451
3   chr1      962727   964530   1804 +      132    ENST00000466300.1  339451
4   chr1      963552   964164    613 +      133    ENST00000481067.1  339451
5   chr1     1615454  1630604  15151 +      245    ENST00000479659.5  142678
6   chr1     1615496  1630604  15109 +      246    ENST00000489635.5  142678
7   chr1     1615500  1630605  15106 +      247    ENST00000355826.10 142678
8   chr1     1615500  1630605  15106 +      248    ENST00000505820.7  142678
9   chr1     1615500  1630605  15106 +      249    ENST00000518681.6  142678
10  chr1     1615500  1630605  15106 +      250    ENST00000520777.6  142678
11  chr1     1615514  1630604  15091 +      251    ENST00000511502.5  142678
12  chr1     1615516  1619210   3695 +      252    ENST00000477990.1  142678
13  chr1     1615530  1625040   9511 +      253    ENST00000514363.1  142678
14  chr1     1615879  1630604  14726 +      254    ENST00000487053.5  142678
15  chr1     1615887  1624832   8946 +      255    ENST00000502470.5  142678
16  chr1     1615905  1630604  14700 +      256    ENST00000378712.5  142678
17  chr1     1615914  1617898   1985 +      257    ENST00000507082.1  142678
18  chr1     1615968  1617323   1356 +      258    ENST00000463492.1  142678
19  chr1     1616274  1624901   8628 +      259    ENST00000510793.5  142678
20  chr1     1616310  1630604  14295 +      260    ENST00000504599.6  142678
21  chr1     1616311  1629163  12853 +      261    ENST00000507229.5  142678
22  chr1     1617408  1624821   7414 +      262    ENST00000503789.5  142678
23  chr1     1617560  1630604  13045 +      263    ENST00000378708.5  142678
24  chr1     1617577  1630532  12956 +      264    ENST00000506488.5  142678
25  chr1     1623122  1624859   1738 +      265    ENST00000512004.1  142678
26  chr1     1623581  1624209    629 +      266    ENST00000508455.1  142678
27  chr1     1623802  1630604   6803 +      267    ENST00000514234.5  142678
28  chr1     1624744  1625799   1056 +      268    ENST00000467597.1  142678
29  chr1     1625087  1625763    677 +      269    ENST00000508148.1  142678
30  chr1     1625567  1626929   1363 +      270    ENST00000486072.1  142678
⋮   ⋮        ⋮        ⋮        ⋮     ⋮      ⋮      ⋮                  ⋮
656 chr20    63658305 63680811 22507 +      232011 ENST00000684971.1  100533107
657 chr20    63659300 63698684 39385 +      232021 ENST00000492259.6  100533107
658 chr20    63686371 63698684 12314 +      232027 ENST00000480273.5  100533107
659 chr20    63688170 63698680 10511 +      232028 ENST00000496281.2  100533107
660 chr20    63689766 63698603  8838 +      232030 ENST00000697815.1  100533107
661 chr20    63707465 63736141 28677 +      232034 ENST00000448100.6      84619
662 chr20    63708039 63736141 28103 +      232035 ENST00000477340.5      84619
663 chr20    63708039 63736142 28104 +      232036 ENST00000355969.11     84619
664 chr20    63708053 63736142 28090 +      232037 ENST00000357119.8      84619
665 chr20    63708062 63708871   810 +      232038 ENST00000431125.1      84619
666 chr20    63708086 63736142 28057 +      232039 ENST00000369967.7      84619
667 chr20    63708090 63736141 28052 +      232040 ENST00000328969.5      84619
668 chr20    63708881 63734824 25944 +      232042 ENST00000472711.5      84619
669 chr20    63708998 63735185 26188 +      232043 ENST00000478385.5      84619
670 chr20    63709089 63733970 24882 +      232044 ENST00000468235.1      84619
671 chr20    63734154 63735236  1083 +      232046 ENST00000484569.1      84619
672 chr20    63698642 63707658  9017 -      235010 ENST00000612256.4      10139
673 chr20    63698643 63707853  9211 -      235011 ENST00000619493.4      10139
674 chr20    63698643 63708013  9371 -      235012 ENST00000614942.4      10139
675 chr20    63698647 63707976  9330 -      235013 ENST00000622789.5      10139
676 chr20    63699456 63700777  1322 -      235014 ENST00000610414.4      10139
677 chr20    63699456 63701388  1933 -      235015 ENST00000612772.1      10139
678 chr20    63699456 63707838  8383 -      235016 ENST00000618838.4      10139
679 chr20    63699478 63707916  8439 -      235017 ENST00000612157.4      10139
680 chr20    63699497 63707996  8500 -      235018 ENST00000618568.4      10139
681 chr20    63699512 63706053  6542 -      235019 ENST00000610774.1      10139
682 chr20    63700054 63708025  7972 -      235021 ENST00000607873.1      10139
683 chr20    63701697 63706874  5178 -      235022 ENST00000609537.5      10139
684 chr20    63705579 63706738  1160 -      235023 ENST00000424545.2      10139
685 chr21    32377187 32377322   136 -      237460 ENST00000363922.1     677846

In [59]:
# Converting to dataframe
tss_df <- as.data.frame(gene_bodies)

# Creating a .bed like table
bed_gene_df <- data.frame(
  chrom = tss_df$seqnames,
  chromStart = tss_df$start - 1,  # BED is 0-based
  chromEnd = tss_df$end,          
  name = tss_df$tx_name,         
  score = 0,
  strand = tss_df$strand
)
#export
write.table(
  bed_gene_df,
  file = "downregulated_transcript_level_genebodies.bed",
  sep = "\t",
  quote = FALSE,
  row.names = FALSE,
  col.names = FALSE
)

In [60]:
bed_gene_df

    chrom chromStart chromEnd name               score strand
1   chr1   960583     965719  ENST00000338591.8  0     +
2   chr1   961448     962478  ENST00000463212.1  0     +
3   chr1   962726     964530  ENST00000466300.1  0     +
4   chr1   963551     964164  ENST00000481067.1  0     +
5   chr1  1615453    1630604  ENST00000479659.5  0     +
6   chr1  1615495    1630604  ENST00000489635.5  0     +
7   chr1  1615499    1630605  ENST00000355826.10 0     +
8   chr1  1615499    1630605  ENST00000505820.7  0     +
9   chr1  1615499    1630605  ENST00000518681.6  0     +
10  chr1  1615499    1630605  ENST00000520777.6  0     +
11  chr1  1615513    1630604  ENST00000511502.5  0     +
12  chr1  1615515    1619210  ENST00000477990.1  0     +
13  chr1  1615529    1625040  ENST00000514363.1  0     +
14  chr1  1615878    1630604  ENST00000487053.5  0     +
15  chr1  1615886    1624832  ENST00000502470.5  0     +
16  chr1  1615904    1630604  ENST00000378712.5  0     +
17  chr1  1615913    1617898  ENST00000507082.1  0     +
18  chr1  1615967    1617323  ENST00000463492.1  0     +
19  chr1  1616273    1624901  ENST00000510793.5  0     +
20  chr1  1616309    1630604  ENST00000504599.6  0     +
21  chr1  1616310    1629163  ENST00000507229.5  0     +
22  chr1  1617407    1624821  ENST00000503789.5  0     +
23  chr1  1617559    1630604  ENST00000378708.5  0     +
24  chr1  1617576    1630532  ENST00000506488.5  0     +
25  chr1  1623121    1624859  ENST00000512004.1  0     +
26  chr1  1623580    1624209  ENST00000508455.1  0     +
27  chr1  1623801    1630604  ENST00000514234.5  0     +
28  chr1  1624743    1625799  ENST00000467597.1  0     +
29  chr1  1625086    1625763  ENST00000508148.1  0     +
30  chr1  1625566    1626929  ENST00000486072.1  0     +
⋮   ⋮     ⋮          ⋮        ⋮                  ⋮     ⋮
656 chr20 63658304   63680811 ENST00000684971.1  0     +
657 chr20 63659299   63698684 ENST00000492259.6  0     +
658 chr20 63686370   63698684 ENST00000480273.5  0     +
659 chr20 63688169   63698680 ENST00000496281.2  0     +
660 chr20 63689765   63698603 ENST00000697815.1  0     +
661 chr20 63707464   63736141 ENST00000448100.6  0     +
662 chr20 63708038   63736141 ENST00000477340.5  0     +
663 chr20 63708038   63736142 ENST00000355969.11 0     +
664 chr20 63708052   63736142 ENST00000357119.8  0     +
665 chr20 63708061   63708871 ENST00000431125.1  0     +
666 chr20 63708085   63736142 ENST00000369967.7  0     +
667 chr20 63708089   63736141 ENST00000328969.5  0     +
668 chr20 63708880   63734824 ENST00000472711.5  0     +
669 chr20 63708997   63735185 ENST00000478385.5  0     +
670 chr20 63709088   63733970 ENST00000468235.1  0     +
671 chr20 63734153   63735236 ENST00000484569.1  0     +
672 chr20 63698641   63707658 ENST00000612256.4  0     -
673 chr20 63698642   63707853 ENST00000619493.4  0     -
674 chr20 63698642   63708013 ENST00000614942.4  0     -
675 chr20 63698646   63707976 ENST00000622789.5  0     -
676 chr20 63699455   63700777 ENST00000610414.4  0     -
677 chr20 63699455   63701388 ENST00000612772.1  0     -
678 chr20 63699455   63707838 ENST00000618838.4  0     -
679 chr20 63699477   63707916 ENST00000612157.4  0     -
680 chr20 63699496   63707996 ENST00000618568.4  0     -
681 chr20 63699511   63706053 ENST00000610774.1  0     -
682 chr20 63700053   63708025 ENST00000607873.1  0     -
683 chr20 63701696   63706874 ENST00000609537.5  0     -
684 chr20 63705578   63706738 ENST00000424545.2  0     -
685 chr21 32377186   32377322 ENST00000363922.1  0     -