---

In [1]:
# gene level

In [2]:
library(AnnotationDbi)
library(org.Hs.eg.db)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(dplyr)
library(rtracklayer)

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Loading required package: IRanges

Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname




Loading required package: GenomicFeatures

Loading required package: GenomeInfoDb

Loading required package: GenomicRanges


Attaching package: ‘dplyr’


The following objects are masked from ‘package:GenomicRanges’:

    intersect, setdiff, union


The following object is masked from ‘package:GenomeInfoDb’:

    intersect


The following object is masked from ‘package:AnnotationDbi’:

    select


The following objects are masked from ‘package:IRanges’:

    collapse, desc, intersect, setdiff, slice, union


The following objects are masked from ‘package:S4Vectors’:

    first, intersect, rename, setdiff, setequal, union


The following object is masked from ‘package:Biobase’:

    combine


The following objects are masked from ‘package:BiocGenerics’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

## Transcript -level TSS

##### first up regulated

In [3]:
mygenes <- read.delim("/usr/users/papantonis1/aman/rnaseq_data/upregulated_genes_deseq.txt", header = TRUE)
mygenes <- mygenes$hgnc_symbol

In [4]:
library(org.Hs.eg.db)

# Map gene symbols to Entrez IDs
mapped <- mapIds(org.Hs.eg.db,
                 keys = mygenes,
                 column = "ENTREZID",
                 keytype = "SYMBOL",
                 multiVals = "first")

# Remove NAs
entrez_ids <- na.omit(mapped)

'select()' returned 1:1 mapping between keys and columns

In [5]:
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
gene_bodies <- genes(txdb)   # direct gene coordinates, keyed by Entrez IDs
gene_bodies <- gene_bodies[names(gene_bodies) %in% entrez_ids]

  2135 genes were dropped because they have exons located on both strands
  of the same reference sequence or on more than one reference sequence,
  so cannot be represented by a single genomic range.
  Use 'single.strand.genes.only=FALSE' to get all the genes in a
  GRangesList object, or use suppressMessages() to suppress this message.

In [7]:
library(GenomicFeatures)

txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene

# 1) One range per gene (Entrez IDs); ambiguous genes dropped by default
gene_bodies <- genes(txdb)                       # GRanges
gene_bodies <- gene_bodies[names(gene_bodies) %in% entrez_ids]

# 2) Convert to BED6 (0-based start)
tss_df <- as.data.frame(gene_bodies)
bed_gene_df <- data.frame(
  chrom      = tss_df$seqnames,
  chromStart = tss_df$start - 1L,   # BED is 0-based, half-open
  chromEnd   = tss_df$end,
  name       = tss_df$gene_id,      # <- correct column name
  score      = 0,
  strand     = as.character(tss_df$strand),
  stringsAsFactors = FALSE
)

stopifnot(nrow(bed_gene_df) == nrow(tss_df))     # sanity check

write.table(
  bed_gene_df,
  file = "upregulated_genelevel_genebodies.bed",
  sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE
)

  2135 genes were dropped because they have exons located on both strands
  of the same reference sequence or on more than one reference sequence,
  so cannot be represented by a single genomic range.
  Use 'single.strand.genes.only=FALSE' to get all the genes in a
  GRangesList object, or use suppressMessages() to suppress this message.

In [ ]:
#tss_df

In [8]:
bed_gene_df

    chrom chromStart chromEnd  name      score strand
1   chr16  68644992   68727468 1001      0     +
2   chrX  101418286  101533459 100131755 0     +
3   chr16  31201884   31203452 100652740 0     +
4   chr5  138178718  138187723 10112     0     +
5   chr3  127480689  127537817 101927149 0     -
6   chr1  149923316  149927803 10262     0     -
7   chr22  30331987   30356919 10291     0     -
8   chr9  137241286  137243707 10383     0     +
9   chr19  41708584   41756737 1048      0     +
10  chr17  43014606   43025123 10493     0     -
11  chr19  16517893   16542437 10523     0     -
12  chr17  45148474   45152099 10614     0     +
13  chr1  154924739  154936719 10654     0     -
14  chr12 106237880  106304279 10970     0     -
15  chr5  150601079  150659207 11346     0     +
16  chr13 113399610  113453488 113622    0     -
17  chr8   27596916   27614700 1191      0     -
18  chr19  44954584   44993341 1209      0     +
19  chr17  79932342   80035872 125058    0     -
20  chr19   2071035    2096673 126308    0     -
21  chr1  151070577  151125542 126626    0     +
22  chr10  69801879   69964275 1305      0     +
23  chr1  207453023  207489895 1380      0     +
24  chr16   3725053    3880713 1387      0     -
25  chr11  95165512   95232541 143686    0     -
26  chr19   4815931    4831712 148022    0     -
27  chr6  131948175  131951372 1490      0     -
28  chr2  112736348  112764664 150468    0     -
29  chr6  133987580  134052624 154091    0     -
30  chrX  112774502  112840831 154796    0     -
⋮   ⋮     ⋮          ⋮         ⋮         ⋮     ⋮
167 chr11  60842112   60851081 79080     0     +
168 chr15  40952961   40956512 79094     0     +
169 chr16  74712954   74774831 79152     0     -
170 chr9   99821854   99866891 8013      0     +
171 chr15  74630557   74696292 80153     0     -
172 chr17  47844907   47855874 80320     0     -
173 chr6  149963942  149973715 80329     0     +
174 chr11  65892048   65900573 8061      0     -
175 chr22  29073034   29168333 83999     0     +
176 chrX   38149335   38220924 8406      0     -
177 chr12  49208545   49274600 84790     0     +
178 chr12 116738177  116853631 84900     0     +
179 chr17  40475827   40501623 84951     0     -
180 chr10 104309697  104338465 85450     0     -
181 chr3    4979436    4985323 8553      0     +
182 chr10   5035353    5107686 8644      0     +
183 chr16  28688557   28735727 8663      0     +
184 chr11  61513713   61581148 9066      0     -
185 chr19  53864762   53876435 91663     0     +
186 chrX  136665546  136780932 9459      0     -
187 chrX   51803006   51902354 9500      0     +
188 chr19  14517084   14565980 9524      0     +
189 chr10 119651379  119677819 9531      0     +
190 chr17  40092792   40100589 9572      0     -
191 chr22  38982346   38992804 9582      0     +
192 chr11  35138881   35232402 960       0     +
193 chr7  149003061  149028662 9601      0     -
194 chr19  14380500   14408725 976       0     +
195 chr1   43358980   43363203 991       0     +
196 chr12   6493355    6531955 9918      0     +

##### now downregulated

In [9]:
mygenes <- read.delim("/usr/users/papantonis1/aman/rnaseq_data/downregulated_genes_deseq.txt", header = TRUE)
mygenes <- mygenes$hgnc_symbol

In [10]:
library(org.Hs.eg.db)

# Map gene symbols to Entrez IDs
mapped <- mapIds(org.Hs.eg.db,
                 keys = mygenes,
                 column = "ENTREZID",
                 keytype = "SYMBOL",
                 multiVals = "first")

# Remove NAs
entrez_ids <- na.omit(mapped)

'select()' returned 1:1 mapping between keys and columns

In [11]:
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene

gene_bodies <- genes(txdb)   # direct gene coordinates, keyed by Entrez IDs
gene_bodies <- gene_bodies[names(gene_bodies) %in% entrez_ids]

  2135 genes were dropped because they have exons located on both strands
  of the same reference sequence or on more than one reference sequence,
  so cannot be represented by a single genomic range.
  Use 'single.strand.genes.only=FALSE' to get all the genes in a
  GRangesList object, or use suppressMessages() to suppress this message.

In [ ]:
#as.data.frame(gene_bodies)

In [12]:
as.data.frame(gene_bodies)

          seqnames start     end       width  strand gene_id
100128893 chr18     22166898  22169878   2981 -      100128893
100288152 chr5        473236    480830   7595 +      100288152
100302743 chr2      10446714  10446849    136 -      100302743
100500819 chr7      98881650  98881729     80 +      100500819
100533107 chr20     63658294  63698684  40391 +      100533107
10139     chr20     63698642  63708025   9384 -      10139
109616975 chr5     139276180 139276320    141 +      109616975
110806276 chr1     221966341 221984964  18624 +      110806276
115294    chr8      51817575  51899186  81612 -      115294
116983    chr1       1292390   1309609  17220 -      116983
142678    chr1       1615454   1630605  15152 +      142678
158056    chr9     136850943 136860799   9857 +      158056
167691    chr6      79484991  79537458  52468 -      167691
1775      chr16      2235816   2238711   2896 +      1775
197335    chr16       649311    667833  18523 +      197335
197342    chr16      1772810   1781708   8899 +      197342
201255    chr17     82023305  82031151   7847 +      201255
23531     chr17     55392622  55421924  29303 -      23531
23642     chr11     62851978  62855953   3976 -      23642
254552    chr11     67627938  67629937   2000 -      254552
26768     chr1      28508559  28508762    204 +      26768
26821     chr5     139278781 139278978    198 +      26821
283229    chr11       826144    831991   5848 +      283229
285613    chr5     141636950 141641064   4115 +      285613
339451    chr1        960584    965719   5136 +      339451
340390    chr8     144107726 144118328  10603 +      340390
3576      chr4      73740519  73743716   3198 +      3576
3622      chr4     183505058 183512429   7372 +      3622
388591    chr1       6205475   6221299  15825 +      388591
389170    chr3     156825481 157046129 220649 +      389170
⋮         ⋮        ⋮         ⋮         ⋮      ⋮      ⋮
54848     chr4     105552620 105695678 143059 +      54848
55582     chr9      83834099  83921465  87367 -      55582
55657     chr1     248850006 248859144   9139 -      55657
56890     chr12     68294566  68332381  37816 -      56890
643911    chr16     54916492  54929189  12698 -      643911
677808    chr11      9428773   9428954    182 +      677808
677829    chr12    132031224 132031359    136 +      677829
677832    chr12     98599635  98599883    249 +      677832
677841    chr5     173020728 173020928    201 +      677841
677846    chr21     32377187  32377322    136 -      677846
692225    chr2      86135870  86136006    137 +      692225
7169      chr9      35681992  35690056   8065 -      7169
780851    chr17     19188016  19188714    699 +      780851
780852    chr17     19063346  19064136    791 -      780852
780853    chr17     19189665  19190245    581 -      780853
79778     chr7       1428465   1459470  31006 -      79778
80114     chr10     58512872  58831435 318564 +      80114
80162     chr11       289126    296107   6982 +      80162
80279     chr17     47945424  47981781  36358 +      80279
84314     chr17      8172457   8176399   3943 -      84314
84619     chr20     63707465  63736142  28678 +      84619
84787     chr19     55339853  55348121   8269 +      84787
84988     chr8     144477969 144502121  24153 +      84988
8558      chr16     89680737  89696354  15618 +      8558
8718      chr1       6460786   6466175   5390 -      8718
898       chr19     29811991  29824312  12322 +      898
9028      chr16       675671    678268   2598 +      9028
9064      chr1      27355184  27366961  11778 -      9064
90990     chr8     144466043 144474202   8160 +      90990
9134      chr8      94879770  94896678  16909 -      9134

In [13]:
# gene_bodies is a GRanges from: gene_bodies <- genes(txdb)
tss_df <- as.data.frame(gene_bodies)   # cols: seqnames, start, end, strand, gene_id, ...

# Build BED6 (0-based, half-open)
bed_gene_df <- data.frame(
  chrom      = tss_df$seqnames,
  chromStart = as.integer(tss_df$start) - 1L,   # BED is 0-based
  chromEnd   = as.integer(tss_df$end),
  name       = as.character(tss_df$gene_id),    # <-- FIXED
  score      = 0,
  strand     = as.character(tss_df$strand),
  stringsAsFactors = FALSE
)

write.table(
  bed_gene_df,
  file = "downregulated_gene_level_genebodies.bed",
  sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE
)

In [14]:
bed_gene_df

   chrom chromStart chromEnd  name      score strand
1  chr18  22166897   22169878 100128893 0     -
2  chr5     473235     480830 100288152 0     +
3  chr2   10446713   10446849 100302743 0     -
4  chr7   98881649   98881729 100500819 0     +
5  chr20  63658293   63698684 100533107 0     +
6  chr20  63698641   63708025 10139     0     -
7  chr5  139276179  139276320 109616975 0     +
8  chr1  221966340  221984964 110806276 0     +
9  chr8   51817574   51899186 115294    0     -
10 chr1    1292389    1309609 116983    0     -
11 chr1    1615453    1630605 142678    0     +
12 chr9  136850942  136860799 158056    0     +
13 chr6   79484990   79537458 167691    0     -
14 chr16   2235815    2238711 1775      0     +
15 chr16    649310     667833 197335    0     +
16 chr16   1772809    1781708 197342    0     +
17 chr17  82023304   82031151 201255    0     +
18 chr17  55392621   55421924 23531     0     -
19 chr11  62851977   62855953 23642     0     -
20 chr11  67627937   67629937 254552    0     -
21 chr1   28508558   28508762 26768     0     +
22 chr5  139278780  139278978 26821     0     +
23 chr11    826143     831991 283229    0     +
24 chr5  141636949  141641064 285613    0     +
25 chr1     960583     965719 339451    0     +
26 chr8  144107725  144118328 340390    0     +
27 chr4   73740518   73743716 3576      0     +
28 chr4  183505057  183512429 3622      0     +
29 chr1    6205474    6221299 388591    0     +
30 chr3  156825480  157046129 389170    0     +
⋮  ⋮     ⋮          ⋮         ⋮         ⋮     ⋮
33 chr4  105552619  105695678 54848     0     +
34 chr9   83834098   83921465 55582     0     -
35 chr1  248850005  248859144 55657     0     -
36 chr12  68294565   68332381 56890     0     -
37 chr16  54916491   54929189 643911    0     -
38 chr11   9428772    9428954 677808    0     +
39 chr12 132031223  132031359 677829    0     +
40 chr12  98599634   98599883 677832    0     +
41 chr5  173020727  173020928 677841    0     +
42 chr21  32377186   32377322 677846    0     -
43 chr2   86135869   86136006 692225    0     +
44 chr9   35681991   35690056 7169      0     -
45 chr17  19188015   19188714 780851    0     +
46 chr17  19063345   19064136 780852    0     -
47 chr17  19189664   19190245 780853    0     -
48 chr7    1428464    1459470 79778     0     -
49 chr10  58512871   58831435 80114     0     +
50 chr11    289125     296107 80162     0     +
51 chr17  47945423   47981781 80279     0     +
52 chr17   8172456    8176399 84314     0     -
53 chr20  63707464   63736142 84619     0     +
54 chr19  55339852   55348121 84787     0     +
55 chr8  144477968  144502121 84988     0     +
56 chr16  89680736   89696354 8558      0     +
57 chr1    6460785    6466175 8718      0     -
58 chr19  29811990   29824312 898       0     +
59 chr16    675670     678268 9028      0     +
60 chr1   27355183   27366961 9064      0     -
61 chr8  144466042  144474202 90990     0     +
62 chr8   94879769   94896678 9134      0     -