In [1]:
# objective is to find the genomic coordinates of all the genes in ranked_genes_list.txt

In [15]:
library(org.Hs.eg.db)
library(GenomicFeatures)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(clusterProfiler)
library(rtracklayer)

In [3]:
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
#genes_gr <- genes(txdb)

  2162 genes were dropped because they have exons located on both strands
  of the same reference sequence or on more than one reference sequence,
  so cannot be represented by a single genomic range.
  Use 'single.strand.genes.only=FALSE' to get all the genes in a
  GRangesList object, or use suppressMessages() to suppress this message.

In [4]:
genes_gr <- genes(txdb, single.strand.genes.only = FALSE)
genes_gr

GRangesList object of length 33131:
$`1`
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]    chr19 58345178-58362751      -
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

$`10`
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]     chr8 18386311-18401218      +
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

$`100`
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]    chr20 44584896-44652252      -
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

...
<33128 more elements>

In [5]:
gene_df <- read.table("/usr/users/papantonis1/aman/rnaseq_data/ranked_gene_list.txt", header=TRUE)

gene_df$ensembl_clean <- sub("\\..*", "", gene_df$ensembl)

# Map to entrezid
mapped <- bitr(gene_df$ensembl_clean,
               fromType = "ENSEMBL",
               toType = "ENTREZID",
               OrgDb = org.Hs.eg.db)
mapped

'select()' returned 1:many mapping between keys and columns

Warning message in bitr(gene_df$ensembl_clean, fromType = "ENSEMBL", toType = "ENTREZID", :
“46.97% of input gene IDs are fail to map...”

      ENSEMBL         ENTREZID
1     ENSG00000290825 84771
2     ENSG00000290825 727856
3     ENSG00000290825 100287102
4     ENSG00000290825 100287596
5     ENSG00000290825 102725121
12    ENSG00000222623 106480049
13    ENSG00000222623 124906683
15    ENSG00000292994 127239154
18    ENSG00000293331 101928626
19    ENSG00000293331 124901156
22    ENSG00000225972 100887749
23    ENSG00000225630 100652939
24    ENSG00000237973 107075141
26    ENSG00000248527 106480796
28    ENSG00000223181 106480091
30    ENSG00000237491 105378580
31    ENSG00000177757 400728
32    ENSG00000228794 643837
33    ENSG00000230368 284593
34    ENSG00000234711 388579
39    ENSG00000223764 100130417
40    ENSG00000187634 148398
41    ENSG00000188976 26155
42    ENSG00000187961 339451
43    ENSG00000187583 84069
44    ENSG00000187642 84808
47    ENSG00000188290 57801
49    ENSG00000187608 9636
53    ENSG00000188157 375790
54    ENSG00000291156 100288175
⋮     ⋮               ⋮
50194 ENSG00000252766 106481258
50196 ENSG00000291031 286554
50197 ENSG00000291031 105377223
50199 ENSG00000291033 246126
50202 ENSG00000012817 8284
50203 ENSG00000288049 105377224
50204 ENSG00000237997 100421075
50207 ENSG00000229236 246119
50209 ENSG00000198692 9086
50211 ENSG00000225624 286555
50212 ENSG00000280969 140032
50215 ENSG00000237427 100499416
50217 ENSG00000289707 105377225
50219 ENSG00000184991 83868
50220 ENSG00000237023 387364
50225 ENSG00000237917 347613
50230 ENSG00000198888 4535
50234 ENSG00000198763 4536
50239 ENSG00000198804 4512
50240 ENSG00000210151 113219467
50242 ENSG00000198712 4513
50243 ENSG00000228253 4509
50244 ENSG00000198899 4508
50245 ENSG00000198938 4514
50246 ENSG00000198840 4537
50247 ENSG00000212907 4539
50248 ENSG00000198886 4538
50250 ENSG00000198786 4540
50251 ENSG00000198695 4541
50253 ENSG00000198727 4519

In [6]:
#mapped$ENTREZID

In [7]:
my_de <- mapped$ENTREZID
genes_gr <- genes_gr[names(genes_gr) %in% my_de]
genes_gr

GRangesList object of length 22612:
$`1`
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]    chr19 58345178-58362751      -
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

$`10`
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]     chr8 18386311-18401218      +
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

$`100`
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]    chr20 44584896-44652252      -
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

...
<22609 more elements>

In [14]:
head(unlist(genes_gr)) # unlist to flat

GRanges object with 6 ranges and 0 metadata columns:
                   seqnames              ranges strand
                      <Rle>           <IRanges>  <Rle>
      1               chr19   58345178-58362751      -
     10                chr8   18386311-18401218      +
    100               chr20   44584896-44652252      -
   1000               chr18   27932879-28177946      -
  10000                chr1 243488233-243851079      -
  10000 chr1_KI270763v1_alt       500341-867542      -
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

In [16]:
# export
ranked_gene_list_bed <- unlist(genes_gr)
export(ranked_gene_list_bed, con = "genes_output.bed", format = "BED")

In [17]:
rg_bed = read.table("genes_output.bed")
head(rg_bed)
# v4 - granges list ele. name, v5 - score, v6 - strand

  V1                  V2        V3        V4    V5 V6
1 chr19                58345177  58362751     1 0  -
2 chr8                 18386310  18401218    10 0  +
3 chr20                44584895  44652252   100 0  -
4 chr18                27932878  28177946  1000 0  -
5 chr1                243488232 243851079 10000 0  -
6 chr1_KI270763v1_alt    500340    867542 10000 0  -

#### Upregulated genes - DeSeq2

In [21]:
upreg_gene_df <- read.table("/usr/users/papantonis1/aman/rnaseq_data/upregulated_genes.txt", header=TRUE)

upreg_gene_df$ensembl_clean <- sub("\\..*", "", upreg_gene_df$ensembl)

# Map to entrezid
mapped_upreg <- bitr(upreg_gene_df$ensembl_clean,
               fromType = "ENSEMBL",
               toType = "ENTREZID",
               OrgDb = org.Hs.eg.db)
mapped_upreg

'select()' returned 1:many mapping between keys and columns

Warning message in bitr(upreg_gene_df$ensembl_clean, fromType = "ENSEMBL", toType = "ENTREZID", :
“0.44% of input gene IDs are fail to map...”

    ENSEMBL         ENTREZID
1   ENSG00000078808 51150
2   ENSG00000049239 9563
3   ENSG00000171603 22883
4   ENSG00000142657 5226
5   ENSG00000083444 5351
6   ENSG00000116731 7799
7   ENSG00000197312 84301
8   ENSG00000142627 1969
9   ENSG00000127463 23065
10  ENSG00000117242 100861548
11  ENSG00000244038 1650
12  ENSG00000117298 1889
13  ENSG00000133216 2048
14  ENSG00000117305 3155
15  ENSG00000179163 2517
16  ENSG00000090020 6548
17  ENSG00000158195 10163
18  ENSG00000130768 27293
19  ENSG00000204138 65979
20  ENSG00000198492 51441
21  ENSG00000060656 10076
22  ENSG00000162512 9672
23  ENSG00000121774 10657
24  ENSG00000025800 23633
25  ENSG00000175130 65108
26  ENSG00000134684 8565
27  ENSG00000126067 5690
28  ENSG00000196182 83931
29  ENSG00000134690 55143
30  ENSG00000188786 4520
⋮   ⋮               ⋮
656 ENSG00000198911 6721
657 ENSG00000198951 4668
658 ENSG00000100243 1727
659 ENSG00000100266 11252
660 ENSG00000075218 51512
661 ENSG00000100426 9889
662 ENSG00000006756 414
663 ENSG00000147010 30011
664 ENSG00000067992 5165
665 ENSG00000101955 8406
666 ENSG00000183337 54880
667 ENSG00000182220 10159
668 ENSG00000180182 9282
669 ENSG00000130985 7317
670 ENSG00000102265 7076
671 ENSG00000179222 9500
672 ENSG00000130119 54552
673 ENSG00000188021 29978
674 ENSG00000089472 9843
675 ENSG00000147100 6567
676 ENSG00000102158 84061
677 ENSG00000133138 54885
678 ENSG00000068366 2182
679 ENSG00000126016 154796
680 ENSG00000186416 55922
681 ENSG00000005893 3920
682 ENSG00000147383 50814
683 ENSG00000147394 7739
684 ENSG00000071553 537
685 ENSG00000160211 2539

In [22]:
upreg_de_genes <- mapped_upreg$ENTREZID
genes_gr_overlap_upreg <- genes_gr[names(genes_gr) %in% upreg_de_genes]
genes_gr_overlap_upreg

GRangesList object of length 681:
$`1001`
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]    chr16 68644993-68727468      +
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

$`100128966`
GRanges object with 1 range and 0 metadata columns:
      seqnames              ranges strand
         <Rle>           <IRanges>  <Rle>
  [1]     chr5 138332105-138337146      +
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

$`100652740`
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]    chr16 31201885-31203452      +
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

...
<678 more elements>

In [23]:
head(unlist(genes_gr_overlap_upreg))

GRanges object with 6 ranges and 0 metadata columns:
            seqnames              ranges strand
               <Rle>           <IRanges>  <Rle>
       1001    chr16   68644993-68727468      +
  100128966     chr5 138332105-138337146      +
  100652740    chr16   31201885-31203452      +
      10076     chr1   29236516-29326813      +
  100861548     chr1   20642657-20652193      -
      10097     chr2   65227788-65271253      +
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

In [24]:
# export
upreg_gene_bed <- unlist(genes_gr_overlap_upreg)
export(upreg_gene_bed, con = "upreg_genes.bed", format = "BED")

In [25]:
upreg_bed = read.table("upreg_genes.bed")
head(upreg_bed)
# v4 - granges list ele. name, v5 - score, v6 - strand

  V1    V2        V3        V4        V5 V6
1 chr16  68644992  68727468      1001 0  +
2 chr5  138332104 138337146 100128966 0  +
3 chr16  31201884  31203452 100652740 0  +
4 chr1   29236515  29326813     10076 0  +
5 chr1   20642656  20652193 100861548 0  -
6 chr2   65227787  65271253     10097 0  +

#### Downregulated genes

In [26]:
downreg_gene_df <- read.table("/usr/users/papantonis1/aman/rnaseq_data/downregulated_genes.txt", header=TRUE)

downreg_gene_df$ensembl_clean <- sub("\\..*", "", downreg_gene_df$ensembl)

# Map to entrezid
mapped_downreg <- bitr(downreg_gene_df$ensembl_clean,
               fromType = "ENSEMBL",
               toType = "ENTREZID",
               OrgDb = org.Hs.eg.db)
mapped_downreg

'select()' returned 1:many mapping between keys and columns

Warning message in bitr(downreg_gene_df$ensembl_clean, fromType = "ENSEMBL", toType = "ENTREZID", :
“8.43% of input gene IDs are fail to map...”

    ENSEMBL         ENTREZID
1   ENSG00000187961 339451
2   ENSG00000131584 116983
3   ENSG00000107404 1855
4   ENSG00000221978 81669
5   ENSG00000197530 142678
6   ENSG00000158286 388591
7   ENSG00000142733 9064
8   ENSG00000200087 26768
9   ENSG00000197989 85028
10  ENSG00000116497 64766
11  ENSG00000081870 51668
12  ENSG00000162599 4774
13  ENSG00000122417 57489
14  ENSG00000274210 124904621
15  ENSG00000143630 57657
16  ENSG00000234741 60674
18  ENSG00000163435 1999
19  ENSG00000143774 2987
20  ENSG00000171163 55657
21  ENSG00000206633 100302743
22  ENSG00000003509 55471
23  ENSG00000116062 2956
24  ENSG00000115392 55120
25  ENSG00000115307 550
26  ENSG00000208772 692225
27  ENSG00000135976 375248
28  ENSG00000196912 57730
29  ENSG00000013441 1195
30  ENSG00000158552 130617
32  ENSG00000178038 259173
⋮   ⋮               ⋮
134 ENSG00000103067 80004
136 ENSG00000185324 8558
137 ENSG00000158805 92822
138 ENSG00000141258 9905
139 ENSG00000183011 84316
143 ENSG00000013306 51629
144 ENSG00000006025 114881
145 ENSG00000108465 80279
146 ENSG00000108960 23531
147 ENSG00000062716 81671
148 ENSG00000136492 83990
149 ENSG00000291117 440456
150 ENSG00000125450 79902
151 ENSG00000182173 283989
152 ENSG00000141524 11322
153 ENSG00000169683 201255
154 ENSG00000169718 64118
155 ENSG00000182087 91304
156 ENSG00000129968 81926
157 ENSG00000105397 7297
158 ENSG00000213339 81890
159 ENSG00000105173 898
160 ENSG00000105443 9266
161 ENSG00000133247 84787
162 ENSG00000026036 100533107
163 ENSG00000101246 10139
164 ENSG00000200792 677846
165 ENSG00000099949 8216
166 ENSG00000100416 55687
167 ENSG00000102030 8260

In [27]:
downreg_de_genes <- mapped_downreg$ENTREZID
genes_gr_overlap_downreg <- genes_gr[names(genes_gr) %in% downreg_de_genes]
genes_gr_overlap_downreg

GRangesList object of length 153:
$`100302743`
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]     chr2 10446714-10446849      -
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

$`100533107`
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]    chr20 63658294-63698684      +
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

$`10139`
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]    chr20 63698642-63708025      -
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

...
<150 more elements>

In [28]:
head(unlist(genes_gr_overlap_downreg))
downreg_gene_bed <- unlist(genes_gr_overlap_downreg)
export(downreg_gene_bed, con = "downreg_genes.bed", format = "BED")

GRanges object with 6 ranges and 0 metadata columns:
            seqnames            ranges strand
               <Rle>         <IRanges>  <Rle>
  100302743     chr2 10446714-10446849      -
  100533107    chr20 63658294-63698684      +
      10139    chr20 63698642-63708025      -
      10142     chr7 91940840-92110673      +
  101927480    chr16 54845189-54874168      -
      10529    chr10 20779973-21293011      -
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

In [29]:
downreg_bed = read.table("downreg_genes.bed")
head(downreg_bed)
# v4 - granges list ele. name, v5 - score, v6 - strand

  V1    V2       V3       V4        V5 V6
1 chr2  10446713 10446849 100302743 0  -
2 chr20 63658293 63698684 100533107 0  +
3 chr20 63698641 63708025     10139 0  -
4 chr7  91940839 92110673     10142 0  +
5 chr16 54845188 54874168 101927480 0  -
6 chr10 20779972 21293011     10529 0  -

----

In [8]:
mega_loops_ctrl <- read.table("/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/merged_loops_3tools/megalooplist/mega_merged_loops_ctrl.bedpe", header=FALSE)
mega_loops_rbp1 <- read.table("/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/merged_loops_3tools/megalooplist/mega_merged_loops_rbp1.bedpe", header=FALSE)
mega_loops_ctrl

      V1   V2        V3        V4   V5        V6
1     chr1 3912500   3917500   chr1  4592500   4597500
2     chr1 5502500   5507500   chr1  5622500   5627500
3     chr1 5502500   5507500   chr1  5742500   5747500
4     chr1 5632500   5637500   chr1  5742500   5747500
5     chr1 5635000   5640000   chr1  5980000   5985000
6     chr1 6555000   6560000   chr1  6645000   6650000
7     chr1 6720000   6725000   chr1  6885000   6890000
8     chr1 6802500   6807500   chr1  6892500   6897500
9     chr1 7032500   7037500   chr1  7202500   7207500
10    chr1 7045000   7050000   chr1  7645000   7650000
11    chr1 7225000   7230000   chr1  7300000   7305000
12    chr1 7972500   7977500   chr1  8322500   8327500
13    chr1 8022500   8027500   chr1  8312500   8317500
14    chr1 8025000   8030000   chr1  8090000   8095000
15    chr1 8025000   8030000   chr1  8170000   8175000
16    chr1 8025000   8030000   chr1  8240000   8245000
17    chr1 8095000   8100000   chr1  8310000   8315000
18    chr1 8362500   8367500   chr1  8722500   8727500
19    chr1 8560000   8565000   chr1  8850000   8855000
20    chr1 8735000   8740000   chr1  8845000   8850000
21    chr1 8912500   8917500   chr1  9002500   9007500
22    chr1 8915000   8920000   chr1  8985000   8990000
23    chr1 8925000   8930000   chr1  9090000   9095000
24    chr1 9010000   9015000   chr1  9100000   9105000
25    chr1 9112500   9117500   chr1  9192500   9197500
26    chr1 9275000   9280000   chr1  9565000   9570000
27    chr1 9280000   9285000   chr1  9490000   9495000
28    chr1 9765000   9770000   chr1  9920000   9925000
29    chr1 9942500   9947500   chr1 10152500  10157500
30    chr1 9952500   9957500   chr1 10422500  10427500
⋮     ⋮    ⋮         ⋮         ⋮    ⋮         ⋮
19007 chrX  16882500  16887500 chrX  17042500  17047500
19008 chrX  17242500  17247500 chrX  17592500  17597500
19009 chrX  19592500  19597500 chrX  19732500  19737500
19010 chrX  22132500  22137500 chrX  22742500  22747500
19011 chrX  26782500  26787500 chrX  27182500  27187500
19012 chrX  26782500  26787500 chrX  27332500  27337500
19013 chrX  26782500  26787500 chrX  27392500  27397500
19014 chrX  35382500  35387500 chrX  35722500  35727500
19015 chrX  39262500  39267500 chrX  39442500  39447500
19016 chrX  43562500  43567500 chrX  43932500  43937500
19017 chrX  57822500  57827500 chrX  58022500  58027500
19018 chrX  68822500  68827500 chrX  69382500  69387500
19019 chrX  69492500  69497500 chrX  70032500  70037500
19020 chrX  70192500  70197500 chrX  70432500  70437500
19021 chrX  70762500  70767500 chrX  70962500  70967500
19022 chrX  71992500  71997500 chrX  72122500  72127500
19023 chrX 103690000 103695000 chrX 103770000 103775000
19024 chrX 110990000 110995000 chrX 111100000 111105000
19025 chrX 114462500 114467500 chrX 114602500 114607500
19026 chrX 130972500 130977500 chrX 131672500 131677500
19027 chrX 132022500 132027500 chrX 132212500 132217500
19028 chrX 150212500 150217500 chrX 150342500 150347500
19029 chrY  10792500  10797500 chrY  11722500  11727500
19030 chrY  10820000  10825000 chrY  11290000  11295000
19031 chrY  10842500  10847500 chrY  11292500  11297500
19032 chrY  10992500  10997500 chrY  11722500  11727500
19033 chrY  11302500  11307500 chrY  11722500  11727500
19034 chrY  11522500  11527500 chrY  11712500  11717500
19035 chrY  11525000  11530000 chrY  11680000  11685000
19036 chrY  20562500  20567500 chrY  20732500  20737500

In [9]:
anchor1_ctrl <- GRanges(seqnames = mega_loops_ctrl$V1,
                   ranges = IRanges(start = mega_loops_ctrl$V2, end = mega_loops_ctrl$V3))

anchor2_ctrl <- GRanges(seqnames = mega_loops_ctrl$V4,
                   ranges = IRanges(start = mega_loops_ctrl$V5, end = mega_loops_ctrl$V6))

anchor2_ctrl

GRanges object with 19036 ranges and 0 metadata columns:
          seqnames            ranges strand
             <Rle>         <IRanges>  <Rle>
      [1]     chr1   4592500-4597500      *
      [2]     chr1   5622500-5627500      *
      [3]     chr1   5742500-5747500      *
      [4]     chr1   5742500-5747500      *
      [5]     chr1   5980000-5985000      *
      ...      ...               ...    ...
  [19032]     chrY 11722500-11727500      *
  [19033]     chrY 11722500-11727500      *
  [19034]     chrY 11712500-11717500      *
  [19035]     chrY 11680000-11685000      *
  [19036]     chrY 20732500-20737500      *
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths

In [10]:
anchor1_rbp1 <- GRanges(seqnames = mega_loops_rbp1$V1,
                   ranges = IRanges(start = mega_loops_rbp1$V2, end = mega_loops_rbp1$V3))

anchor2_rbp1 <- GRanges(seqnames = mega_loops_rbp1$V4,
                   ranges = IRanges(start = mega_loops_rbp1$V5, end = mega_loops_rbp1$V6))

anchor2_rbp1

GRanges object with 16599 ranges and 0 metadata columns:
          seqnames            ranges strand
             <Rle>         <IRanges>  <Rle>
      [1]     chr1   4065000-4070000      *
      [2]     chr1   4155000-4160000      *
      [3]     chr1   5622500-5627500      *
      [4]     chr1   5732500-5737500      *
      [5]     chr1   5752500-5757500      *
      ...      ...               ...    ...
  [16595]     chrY 11722500-11727500      *
  [16596]     chrY 11712500-11717500      *
  [16597]     chrY 11680000-11685000      *
  [16598]     chrY 11760000-11765000      *
  [16599]     chrY 20742500-20747500      *
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths

In [11]:
hits_a1_ctrl <- findOverlaps(anchor1_ctrl, genes_gr)
hits_a2_ctrl <- findOverlaps(anchor2_ctrl, genes_gr)
hits_a1_ctrl

Hits object with 12515 hits and 0 metadata columns:
          queryHits subjectHits
          <integer>   <integer>
      [1]         1         285
      [2]         6       19849
      [3]         8        8521
      [4]         9        8521
      [5]        10        8521
      ...       ...         ...
  [12511]     19021       15720
  [12512]     19022       11287
  [12513]     19027       14204
  [12514]     19028         351
  [12515]     19036        8897
  -------
  queryLength: 19036 / subjectLength: 22612

In [12]:
hits_a1_rbp1 <- findOverlaps(anchor1_rbp1, genes_gr)
hits_a2_rbp1 <- findOverlaps(anchor2_rbp1, genes_gr)
hits_a1_rbp1

Hits object with 10863 hits and 0 metadata columns:
          queryHits subjectHits
          <integer>   <integer>
      [1]         1         285
      [2]         2         285
      [3]         9        8521
      [4]        10        8521
      [5]        11        4575
      ...       ...         ...
  [10859]     16574        7306
  [10860]     16579       18744
  [10861]     16583        9820
  [10862]     16584        3005
  [10863]     16587         351
  -------
  queryLength: 16599 / subjectLength: 22612

In [13]:
hits_a2_ctrl

Hits object with 12655 hits and 0 metadata columns:
          queryHits subjectHits
          <integer>   <integer>
      [1]         5        9463
      [2]         6       15466
      [3]         7        8521
      [4]         8        8521
      [5]         9        8521
      ...       ...         ...
  [12651]     19023       13825
  [12652]     19023       14378
  [12653]     19025       11104
  [12654]     19027        2092
  [12655]     19027       16448
  -------
  queryLength: 19036 / subjectLength: 22612